"""
empty message

Revision ID: 4e16a2ae1734
Revises: 7bbebc0cf4b6
Create Date: 2026-09-16 20:21:33.536334
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4e16a2ae1734'
down_revision: str | Sequence[str] | None = '7bbebc0cf4b6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_tokens', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_auth_tokens_user_id'), 'auth_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_tokens_user_id'), table_name='auth_tokens')
    op.drop_column('auth_tokens', 'revoked_at')
    # ### end Alembic commands ###
