"""
empty message

Revision ID: cbc43608eaee
Revises: e870ac3a7fea
Create Date: 2026-09-12 23:45:34.930925
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbc43608eaee'
down_revision: str | Sequence[str] | None = 'e870ac3a7fea'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'settings',
        sa.Column('language', sa.Enum('RU', 'EN', name='languagetype'), nullable=False),
        sa.Column('theme', sa.Enum('WHITE', 'BLACK', name='themetype'), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'users_permissions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('permission_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.alter_column(
        'auth_tokens',
        'expires_at',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        'auth_tokens',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'registration_tokens',
        'expires_at',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        'registration_tokens',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.drop_constraint(op.f('roles_permissions_permission_id_fkey'), 'roles_permissions', type_='foreignkey')
    op.drop_constraint(op.f('roles_permissions_role_id_fkey'), 'roles_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'roles_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'roles_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.alter_column(
        'users',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'users',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.drop_constraint(op.f('users_roles_user_id_fkey'), 'users_roles', type_='foreignkey')
    op.drop_constraint(op.f('users_roles_role_id_fkey'), 'users_roles', type_='foreignkey')
    op.create_foreign_key(None, 'users_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_roles', type_='foreignkey')
    op.drop_constraint(None, 'users_roles', type_='foreignkey')
    op.create_foreign_key(op.f('users_roles_role_id_fkey'), 'users_roles', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('users_roles_user_id_fkey'), 'users_roles', 'users', ['user_id'], ['id'])
    op.alter_column(
        'users',
        'updated_at',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        'users',
        'created_at',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.drop_constraint(None, 'roles_permissions', type_='foreignkey')
    op.drop_constraint(None, 'roles_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('roles_permissions_role_id_fkey'), 'roles_permissions', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(
        op.f('roles_permissions_permission_id_fkey'),
        'roles_permissions',
        'permissions',
        ['permission_id'],
        ['id'],
    )
    op.alter_column(
        'registration_tokens',
        'created_at',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'registration_tokens',
        'expires_at',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        'auth_tokens',
        'created_at',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'auth_tokens',
        'expires_at',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_table('users_permissions')
    op.drop_table('settings')
    # ### end Alembic commands ###
