"""
empty message

Revision ID: 7bbebc0cf4b6
Revises: cbc43608eaee
Create Date: 2026-09-14 15:14:38.983944
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7bbebc0cf4b6'
down_revision: str | Sequence[str] | None = 'cbc43608eaee'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('roles_permissions_role_id_permission_id_key'), 'roles_permissions', type_='unique')
    op.create_unique_constraint(op.f('uq_roles_permissions_role_id'), 'roles_permissions', ['role_id', 'permission_id'])
    op.create_index(op.f('ix_settings_user_id'), 'settings', ['user_id'], unique=True)
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'password')
    op.create_unique_constraint(op.f('uq_users_permissions_user_id'), 'users_permissions', ['user_id', 'permission_id'])
    op.drop_constraint(op.f('users_roles_user_id_role_id_key'), 'users_roles', type_='unique')
    op.create_unique_constraint(op.f('uq_users_roles_user_id'), 'users_roles', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_roles_user_id'), 'users_roles', type_='unique')
    op.create_unique_constraint(
        op.f('users_roles_user_id_role_id_key'),
        'users_roles',
        ['user_id', 'role_id'],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(op.f('uq_users_permissions_user_id'), 'users_permissions', type_='unique')
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'hashed_password')
    op.drop_index(op.f('ix_settings_user_id'), table_name='settings')
    op.drop_constraint(op.f('uq_roles_permissions_role_id'), 'roles_permissions', type_='unique')
    op.create_unique_constraint(
        op.f('roles_permissions_role_id_permission_id_key'),
        'roles_permissions',
        ['role_id', 'permission_id'],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
