"""
empty message

Revision ID: 36fbf85d877a
Revises:
Create Date: 2026-09-18 11:21:48.909369
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36fbf85d877a'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('white', 'black', 'system', name='settings_theme_enum').create(op.get_bind())
    sa.Enum('ru', 'en', name='settings_language_enum').create(op.get_bind())
    sa.Enum('admin', 'stuff', 'client', name='user_role_enum').create(op.get_bind())
    op.create_table(
        'permissions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table(
        'roles',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('email', sa.String(length=256), nullable=False),
        sa.Column('name', sa.String(length=512), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column(
            'role',
            postgresql.ENUM('admin', 'stuff', 'client', name='user_role_enum', create_type=False),
            nullable=False,
        ),
        sa.Column('is_confirmed', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table(
        'roles_permissions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.Column('permission_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['permission_id'],
            ['permissions.id'],
            name=op.f('fk_roles_permissions_permission_id_permissions'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['role_id'],
            ['roles.id'],
            name=op.f('fk_roles_permissions_role_id_roles'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_roles_permissions')),
        sa.UniqueConstraint('role_id', 'permission_id', name=op.f('uq_roles_permissions_role_id')),
    )
    op.create_table(
        'settings',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            'language',
            postgresql.ENUM('ru', 'en', name='settings_language_enum', create_type=False),
            nullable=False,
        ),
        sa.Column(
            'theme',
            postgresql.ENUM('white', 'black', 'system', name='settings_theme_enum', create_type=False),
            nullable=False,
        ),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_settings_user_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_settings')),
    )
    op.create_index(op.f('ix_settings_user_id'), 'settings', ['user_id'], unique=True)
    op.create_table(
        'users_permissions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('permission_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['permission_id'],
            ['permissions.id'],
            name=op.f('fk_users_permissions_permission_id_permissions'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
            name=op.f('fk_users_permissions_user_id_users'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_users_permissions')),
        sa.UniqueConstraint('user_id', 'permission_id', name=op.f('uq_users_permissions_user_id')),
    )
    op.create_table(
        'users_roles',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['role_id'],
            ['roles.id'],
            name=op.f('fk_users_roles_role_id_roles'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
            name=op.f('fk_users_roles_user_id_users'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_users_roles')),
        sa.UniqueConstraint('user_id', 'role_id', name=op.f('uq_users_roles_user_id')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_roles')
    op.drop_table('users_permissions')
    op.drop_index(op.f('ix_settings_user_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_table('roles_permissions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    sa.Enum('admin', 'stuff', 'client', name='user_role_enum').drop(op.get_bind())
    sa.Enum('ru', 'en', name='settings_language_enum').drop(op.get_bind())
    sa.Enum('white', 'black', 'system', name='settings_theme_enum').drop(op.get_bind())
    # ### end Alembic commands ###
