"""
empty message

Revision ID: a5c2dd87ca21
Revises: 36fbf85d877a
Create Date: 2026-09-18 11:22:16.348774
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5c2dd87ca21'
down_revision: str | Sequence[str] | None = '36fbf85d877a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('access', 'refresh', name='auth_token_type_enum').create(op.get_bind())
    sa.Enum('email_confirmation', 'password_reset', name='registration_token_type_enum').create(op.get_bind())
    op.create_table(
        'auth_tokens',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            'type',
            postgresql.ENUM('access', 'refresh', name='auth_token_type_enum', create_type=False),
            nullable=False,
        ),
        sa.Column('jti', sa.Uuid(), nullable=False),
        sa.Column('token_hash', sa.String(length=256), nullable=False),
        sa.Column('user_agent', sa.String(length=512), nullable=True),
        sa.Column('ip_address', sa.String(length=64), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('family_id', sa.Uuid(), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
            name=op.f('fk_auth_tokens_user_id_users'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_tokens')),
    )
    op.create_index(op.f('ix_auth_tokens_family_id'), 'auth_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_auth_tokens_jti'), 'auth_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_auth_tokens_token_hash'), 'auth_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_auth_tokens_user_id'), 'auth_tokens', ['user_id'], unique=False)
    op.create_table(
        'registration_tokens',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('token_hash', sa.String(), nullable=False),
        sa.Column('used_at', sa.DateTime(), nullable=True),
        sa.Column(
            'type',
            postgresql.ENUM(
                'email_confirmation',
                'password_reset',
                name='registration_token_type_enum',
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column('attempts', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
            name=op.f('fk_registration_tokens_user_id_users'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_registration_tokens')),
    )
    op.create_index(op.f('ix_registration_tokens_token_hash'), 'registration_tokens', ['token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_tokens_token_hash'), table_name='registration_tokens')
    op.drop_table('registration_tokens')
    op.drop_index(op.f('ix_auth_tokens_user_id'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_token_hash'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_jti'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_family_id'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    sa.Enum('email_confirmation', 'password_reset', name='registration_token_type_enum').drop(op.get_bind())
    sa.Enum('access', 'refresh', name='auth_token_type_enum').drop(op.get_bind())
    # ### end Alembic commands ###
