"""empty message

Revision ID: e4a5f81b7f4a
Revises: 3f1ea79de8ae
Create Date: 2026-10-05 15:22:38.647925

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e4a5f81b7f4a'
down_revision: str | Sequence[str] | None = '3f1ea79de8ae'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_tokens_jti'), table_name='auth_tokens')
    op.drop_column('auth_tokens', 'jti')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_tokens', sa.Column('jti', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_auth_tokens_jti'), 'auth_tokens', ['jti'], unique=True)
    # ### end Alembic commands ###
