from typing import Final

EMAIL_CONFIRMATION_TOKEN_EXP_TIME_SEC: Final[int] = 60 * 60 * 15
EMAIL_CONFIRMATION_CODE_LENGTH: Final[int] = 5

ACCESS_TOKEN_EXP_TIME_SEC: Final[int] = 60 * 15
REFRESH_TOKEN_EXP_TIME_SEC: Final[int] = 60 * 60 * 24 * 30
