"""empty message

Revision ID: 40afc054630d
Revises: 4026db55f82d
Create Date: 2026-07-01 18:50:19.260197

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '40afc054630d'
down_revision: str | Sequence[str] | None = '4026db55f82d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'auth_tokens',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('type', sa.Enum('REFRESH', name='authtokentype'), nullable=False),
        sa.Column('expiration_date', sa.DateTime(), nullable=False),
        sa.Column('hash_token', sa.String(), nullable=False),
        sa.Column('user_agent', sa.String(), nullable=True),
        sa.Column('ip_address', sa.String(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'registration_tokens',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('token_hash', sa.String(), nullable=False),
        sa.Column('used_at', sa.DateTime(), nullable=True),
        sa.Column(
            'type', sa.Enum('EMAIL_CONFIRMATION', 'PASSWORD_RESET', name='registrationtokentype'), nullable=False
        ),
        sa.Column('attempts', sa.Integer(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration_tokens')
    op.drop_table('auth_tokens')
    sa.Enum('REFRESH', name='authtokentype').drop(op.get_bind())
    sa.Enum('EMAIL_CONFIRMATION', 'PASSWORD_RESET', name='registrationtokentype').drop(op.get_bind())
    # ### end Alembic commands ###
