"""empty message

Revision ID: 2ce8bbeac8f2
Revises: 0ee35930b00f
Create Date: 2026-07-10 13:20:07.465801

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2ce8bbeac8f2'
down_revision: str | Sequence[str] | None = '0ee35930b00f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('registration_tokens_user_id_fkey'), 'registration_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'registration_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registration_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('registration_tokens_user_id_fkey'), 'registration_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
